# Travis CI checks for pajbot

language: python
sudo: false
cache: pip

python:
  - 3.5

services:
  - mysql
  - redis-server

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
  - pip install -r requirements.txt
  - cp ./install/config.example.ini ./config.ini

script:
  - cd tests && ./tests.py
  - flake8
