# Travis CI checks for tyggbot

language: python

python:
  - 3.4

install:
  - pip install -r pip-requirements.txt --use-mirrors
  - cp install/config.example.ini config.ini

script:
  - cd tests && ./tests.py
