# Travis CI checks for pajbot

language: python
sudo: false
cache: pip

python:
  - 3.7.2

services:
  - mysql
  - redis-server

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot
  - pip install pip flake8 flake8-quotes flake8-import-order --upgrade
  - flake8

install:
  - pip install -U -r requirements.txt
  - cp ./install/config.example.ini ./config.ini

script:
  - cd tests && ./tests.py
