"""Added an added_by column to the StreamChunkHighlight table

Revision ID: 0da1ccff3d2f
Revises: c5459ad11f
Create Date: 2016-03-01 22:37:19.142620

"""

# revision identifiers, used by Alembic.
revision = "0da1ccff3d2f"
down_revision = "c5459ad11f"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_stream_chunk_highlight", sa.Column("created_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tb_stream_chunk_highlight", "tb_user", ["created_by"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tb_stream_chunk_highlight", type_="foreignkey")
    op.drop_column("tb_stream_chunk_highlight", "created_by")
    ### end Alembic commands ###
