"""added user id to pleblist song request

Revision ID: 100b2d456262
Revises: 2c2a6b0b68ca
Create Date: 2016-04-05 23:05:49.758647

"""

# revision identifiers, used by Alembic.
revision = "100b2d456262"
down_revision = "2c2a6b0b68ca"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_pleblist_song", sa.Column("user_id", sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_pleblist_song", "user_id")
    ### end Alembic commands ###
