"""Broadcast ID is no longer unique for each stream chunk.
A new stream chunk can be created if the video, for some reason, has been split up.

Revision ID: 13d4095fb11
Revises: 21f77e60814
Create Date: 2016-01-01 00:38:16.276285

"""

# revision identifiers, used by Alembic.
revision = "13d4095fb11"
down_revision = "21f77e60814"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("broadcast_id", table_name="tb_stream_chunk")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index("broadcast_id", "tb_stream_chunk", ["broadcast_id"], unique=True)
    ### end Alembic commands ###
