"""Added a skip_after to the pleblist song table

Revision ID: 141d961aeb1
Revises: 2a781b2aafa
Create Date: 2016-01-09 03:05:26.655828

"""

# revision identifiers, used by Alembic.
revision = "141d961aeb1"
down_revision = "2a781b2aafa"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_pleblist_song", sa.Column("skip_after", sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_pleblist_song", "skip_after")
    ### end Alembic commands ###
