"""Thumbnail column in highlight can now be nullable

Revision ID: 155eda5d09d
Revises: 30380ad5731
Create Date: 2015-12-20 02:55:58.365130

"""

# revision identifiers, used by Alembic.
revision = "155eda5d09d"
down_revision = "30380ad5731"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tb_stream_chunk_highlight", "thumbnail", existing_type=mysql.TINYINT(display_width=1), nullable=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tb_stream_chunk_highlight", "thumbnail", existing_type=mysql.TINYINT(display_width=1), nullable=False
    )
    ### end Alembic commands ###
