"""Removed the MOTD table

Revision ID: 162dd748b57
Revises: 4db5dc4bc98
Create Date: 2015-12-23 18:55:15.373225

"""

# revision identifiers, used by Alembic.
revision = "162dd748b57"
down_revision = "4db5dc4bc98"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_motd")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_motd",
        sa.Column("id", mysql.INTEGER(display_width=11), nullable=False),
        sa.Column("message", mysql.VARCHAR(length=400), nullable=True),
        sa.Column("enabled", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    ### end Alembic commands ###
