"""User.username is now indexed and unique

Revision ID: 2428871e01d
Revises: 46e47b8f160
Create Date: 2015-11-05 11:03:46.172757

"""

# revision identifiers, used by Alembic.
revision = "2428871e01d"
down_revision = "46e47b8f160"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tb_user", "username", existing_type=mysql.VARCHAR(length=128), nullable=False)
    op.create_index(op.f("ix_tb_user_username"), "tb_user", ["username"], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tb_user_username"), table_name="tb_user")
    op.alter_column("tb_user", "username", existing_type=mysql.VARCHAR(length=128), nullable=True)
    ### end Alembic commands ###
