"""Added token cost column to commands

Revision ID: 250c02ec0e2
Revises: 47bd378fd30
Create Date: 2016-01-19 00:09:22.572365

"""

# revision identifiers, used by Alembic.
revision = "250c02ec0e2"
down_revision = "47bd378fd30"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_command", sa.Column("tokens_cost", sa.Integer(), server_default="0", nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_command", "tokens_cost")
    ### end Alembic commands ###
