"""Added a table for command examples

Revision ID: 25b4e344aa4
Revises: 4d137ce12e
Create Date: 2015-12-18 00:32:39.612945

"""

# revision identifiers, used by Alembic.
revision = "25b4e344aa4"
down_revision = "4d137ce12e"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_command_example",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("command_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("chat", mysql.TEXT(), nullable=False),
        sa.ForeignKeyConstraint(["command_id"], ["tb_command.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_command_example")
    ### end Alembic commands ###
