"""removed unused columns in user table

Revision ID: 25cf8a00d471
Revises: 34d6f5a24cbe
Create Date: 2016-04-10 13:29:45.695493

"""

# revision identifiers, used by Alembic.
revision = "25cf8a00d471"
down_revision = "34d6f5a24cbe"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column("tb_user", "twitch_access_token")
        op.drop_column("tb_user", "twitch_refresh_token")
        op.drop_column("tb_user", "discord_user_id")
    except:
        pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_user", sa.Column("discord_user_id", mysql.VARCHAR(length=32), nullable=True))
    op.add_column("tb_user", sa.Column("twitch_refresh_token", mysql.VARCHAR(length=128), nullable=True))
    op.add_column("tb_user", sa.Column("twitch_access_token", mysql.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###
