"""Removed the settings table

Revision ID: 2a781b2aafa
Revises: 13d4095fb11
Create Date: 2016-01-07 01:08:42.720734

"""

# revision identifiers, used by Alembic.
revision = "2a781b2aafa"
down_revision = "13d4095fb11"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_settings")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_settings",
        sa.Column("id", mysql.INTEGER(display_width=11), nullable=False),
        sa.Column("setting", mysql.VARCHAR(length=128), nullable=True),
        sa.Column("value", mysql.TEXT(), nullable=True),
        sa.Column("type", mysql.VARCHAR(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    ### end Alembic commands ###
