"""Added a thumbnail column to Highlights, in case they have a custom thumbnail

Revision ID: 30380ad5731
Revises: 30d8f26c3e
Create Date: 2015-12-20 01:55:39.460444

"""

# revision identifiers, used by Alembic.
revision = "30380ad5731"
down_revision = "30d8f26c3e"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_stream_chunk_highlight", sa.Column("thumbnail", sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_stream_chunk_highlight", "thumbnail")
    ### end Alembic commands ###
