"""Added a description column to command examples

Revision ID: 30d8f26c3e
Revises: 25b4e344aa4
Create Date: 2015-12-19 00:07:26.472849

"""

# revision identifiers, used by Alembic.
revision = "30d8f26c3e"
down_revision = "25b4e344aa4"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_command_example", sa.Column("description", sa.String(length=512), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_command_example", "description")
    ### end Alembic commands ###
