"""Added a table for custom content on the website

Revision ID: 32f05bdc22
Revises: 38e60e552e
Create Date: 2015-11-25 00:00:21.813437

"""

# revision identifiers, used by Alembic.
revision = "32f05bdc22"
down_revision = "38e60e552e"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_web_content",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("page", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_web_content")
    ### end Alembic commands ###
