"""Added a bunch of default values to the User table

Revision ID: 354eb71928d
Revises: 2428871e01d
Create Date: 2015-11-05 11:30:36.533431

"""

# revision identifiers, used by Alembic.
revision = "354eb71928d"
down_revision = "2428871e01d"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tb_user", "banned", existing_type=mysql.TINYINT(display_width=1), nullable=False)
    op.alter_column("tb_user", "ignored", existing_type=mysql.TINYINT(display_width=1), nullable=False)
    op.alter_column("tb_user", "level", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column("tb_user", "minutes_in_chat_offline", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column("tb_user", "minutes_in_chat_online", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column("tb_user", "num_lines", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column("tb_user", "points", existing_type=mysql.INTEGER(display_width=11), nullable=False)
    op.alter_column("tb_user", "subscriber", existing_type=mysql.TINYINT(display_width=1), nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tb_user", "subscriber", existing_type=mysql.TINYINT(display_width=1), nullable=True)
    op.alter_column("tb_user", "points", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column("tb_user", "num_lines", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column("tb_user", "minutes_in_chat_online", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column("tb_user", "minutes_in_chat_offline", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column("tb_user", "level", existing_type=mysql.INTEGER(display_width=11), nullable=True)
    op.alter_column("tb_user", "ignored", existing_type=mysql.TINYINT(display_width=1), nullable=True)
    op.alter_column("tb_user", "banned", existing_type=mysql.TINYINT(display_width=1), nullable=True)
    ### end Alembic commands ###
