"""Added a "sub immunity" column to tb_banphrase

Revision ID: 361a148f219
Revises: 250c02ec0e2
Create Date: 2016-01-19 23:31:13.203971

"""

# revision identifiers, used by Alembic.
revision = "361a148f219"
down_revision = "250c02ec0e2"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_banphrase", sa.Column("sub_immunity", sa.Boolean(), server_default=sa.text("false"), nullable=False)
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_banphrase", "sub_immunity")
    ### end Alembic commands ###
