"""Added a last_edited_by column to the StreamChunkHighlight table

Revision ID: 406575186b81
Revises: 0da1ccff3d2f
Create Date: 2016-03-01 23:34:49.394440

"""

# revision identifiers, used by Alembic.
revision = "406575186b81"
down_revision = "0da1ccff3d2f"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_stream_chunk_highlight", sa.Column("last_edited_by", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "tb_stream_chunk_highlight", "tb_user", ["last_edited_by"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tb_stream_chunk_highlight", type_="foreignkey")
    op.drop_column("tb_stream_chunk_highlight", "last_edited_by")
    ### end Alembic commands ###
