"""empty message

Revision ID: 46d07701a90b
Revises: 093b91955d73
Create Date: 2019-05-25 11:18:51.199451

"""

# revision identifiers, used by Alembic.
revision = "46d07701a90b"
down_revision = "093b91955d73"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_playsound",
        sa.Column("name", sa.String(length=190), nullable=False),
        sa.Column("link", sa.TEXT(), nullable=False),
        sa.Column("volume", sa.Integer(), nullable=False),
        sa.Column("cooldown", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.drop_table("tb_whisper_account")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_whisper_account",
        sa.Column("username", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128), nullable=False),
        sa.Column("oauth", mysql.VARCHAR(collation="utf8mb4_unicode_ci", length=128), nullable=True),
        sa.Column("enabled", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.CheckConstraint("`enabled` in (0,1)", name="CONSTRAINT_1"),
        sa.PrimaryKeyConstraint("username"),
        mysql_collate="utf8mb4_unicode_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.drop_table("tb_playsound")
    # ### end Alembic commands ###
