"""Added the deck table

Revision ID: 46e47b8f160
Revises: 4f48d3dd0fb
Create Date: 2015-11-04 00:03:57.770809

"""

# revision identifiers, used by Alembic.
revision = "46e47b8f160"
down_revision = "4f48d3dd0fb"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_deck",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=True),
        sa.Column("class", sa.String(length=128), nullable=True),
        sa.Column("link", sa.String(length=256), nullable=True),
        sa.Column("first_used", sa.DateTime(), nullable=True),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.Column("times_used", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_deck")
    ### end Alembic commands ###
