"""Made user_id in tb_user_duel_stats into a foreign key

Revision ID: 4a7ace75092
Revises: 3841cd597e
Create Date: 2015-12-02 02:39:26.718982

"""

# revision identifiers, used by Alembic.
revision = "4a7ace75092"
down_revision = "3841cd597e"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, "tb_user_duel_stats", "tb_user", ["user_id"], ["id"])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "tb_user_duel_stats", type_="foreignkey")
    ### end Alembic commands ###
