"""added hsbet stats tables

Revision ID: 4bd5aca6cf54
Revises: 406575186b81
Create Date: 2016-03-02 22:23:53.950054

"""

# revision identifiers, used by Alembic.
revision = "4bd5aca6cf54"
down_revision = "406575186b81"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_hsbet_game",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("internal_id", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.Enum("win", "loss", name="win_or_loss"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tb_hsbet_bet",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.Enum("win", "loss", name="win_or_loss"), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("profit", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["tb_hsbet_game.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["tb_user.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tb_hsbet_bet_game_id"), "tb_hsbet_bet", ["game_id"], unique=False)
    op.create_index(op.f("ix_tb_hsbet_bet_user_id"), "tb_hsbet_bet", ["user_id"], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tb_hsbet_bet_user_id"), table_name="tb_hsbet_bet")
    op.drop_index(op.f("ix_tb_hsbet_bet_game_id"), table_name="tb_hsbet_bet")
    op.drop_table("tb_hsbet_bet")
    op.drop_table("tb_hsbet_game")
    ### end Alembic commands ###
