"""Removed num_uses from the tb_command table

Revision ID: 4d137ce12e
Revises: 5393671cca7
Create Date: 2015-12-15 04:04:06.689897

"""

# revision identifiers, used by Alembic.
revision = "4d137ce12e"
down_revision = "5393671cca7"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_command", "num_uses")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tb_command", sa.Column("num_uses", mysql.INTEGER(display_width=11), autoincrement=False, nullable=False)
    )
    ### end Alembic commands ###
