"""Added a table for timed commands

Revision ID: 4db5dc4bc98
Revises: 514f4b9bc74
Create Date: 2015-12-23 00:00:59.156496

"""

# revision identifiers, used by Alembic.
revision = "4db5dc4bc98"
down_revision = "514f4b9bc74"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_timer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("action", mysql.TEXT(), nullable=False),
        sa.Column("interval_online", sa.Integer(), nullable=False),
        sa.Column("interval_offline", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_timer")
    ### end Alembic commands ###
