"""Add remove accents option to banphrases

Revision ID: 514603f2ff1f
Revises: 280554f8c9ec
Create Date: 2017-04-10 07:25:23.586754

"""

# revision identifiers, used by Alembic.
revision = "514603f2ff1f"
down_revision = "280554f8c9ec"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_banphrase", sa.Column("remove_accents", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_banphrase", "remove_accents")
    # ### end Alembic commands ###
