"""Added columns for duel win/lose streaks in the tb_user_duel_stats table

Revision ID: 514f4b9bc74
Revises: 1d6dbeb93c9
Create Date: 2015-12-22 00:17:51.509756

"""

# revision identifiers, used by Alembic.
revision = "514f4b9bc74"
down_revision = "1d6dbeb93c9"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_user_duel_stats", sa.Column("current_streak", sa.Integer(), nullable=False))
    op.add_column("tb_user_duel_stats", sa.Column("longest_losestreak", sa.Integer(), nullable=False))
    op.add_column("tb_user_duel_stats", sa.Column("longest_winstreak", sa.Integer(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_user_duel_stats", "longest_winstreak")
    op.drop_column("tb_user_duel_stats", "longest_losestreak")
    op.drop_column("tb_user_duel_stats", "current_streak")
    ### end Alembic commands ###
