"""Created a table for modules

Revision ID: 557eef06651
Revises: 296bac0056a
Create Date: 2015-12-28 02:00:54.345979

"""

# revision identifiers, used by Alembic.
revision = "557eef06651"
down_revision = "296bac0056a"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table("tb_module", sa.Column("id", sa.String(length=64), nullable=False), sa.PrimaryKeyConstraint("id"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_module")
    ### end Alembic commands ###
