"""Added a mod_only flag to commands

Revision ID: 59a5d12aa83
Revises: 2eb59605e7b
Create Date: 2015-11-18 23:23:44.437920

"""

# revision identifiers, used by Alembic.
revision = "59a5d12aa83"
down_revision = "2eb59605e7b"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_commands", sa.Column("mod_only", sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_commands", "mod_only")
    ### end Alembic commands ###
