"""Added a flag to commands if it should be run through the banphrases

Revision ID: 8feba263d722
Revises: a6f9b5c3ba83
Create Date: 2016-05-24 22:04:49.803097

"""

# revision identifiers, used by Alembic.
revision = "8feba263d722"
down_revision = "a6f9b5c3ba83"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_command", sa.Column("run_through_banphrases", sa.Boolean(), server_default="0", nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_command", "run_through_banphrases")
    ### end Alembic commands ###
