"""removed a foreign key

Revision ID: c1c83c09da93
Revises: 4bd5aca6cf54
Create Date: 2016-03-03 00:33:59.443455

"""

# revision identifiers, used by Alembic.
revision = "c1c83c09da93"
down_revision = "4bd5aca6cf54"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tb_hsbet_bet_ibfk_2", "tb_hsbet_bet", type_="foreignkey")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key("tb_hsbet_bet_ibfk_2", "tb_hsbet_bet", "tb_user", ["user_id"], ["id"])
    ### end Alembic commands ###
