"""Added a column for a third party video URL in the StreamChunkHighlight table

Revision ID: d5f1b8bd68
Revises: 278a47e21d5
Create Date: 2015-11-28 19:04:01.296208

"""

# revision identifiers, used by Alembic.
revision = "d5f1b8bd68"
down_revision = "278a47e21d5"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tb_stream_chunk_highlight", sa.Column("override_link", sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tb_stream_chunk_highlight", "override_link")
    ### end Alembic commands ###
