"""empty message

Revision ID: d65267bb8b5e
Revises: 093b91955d73
Create Date: 2019-05-25 11:15:33.336707

"""

# revision identifiers, used by Alembic.
revision = 'd65267bb8b5e'
down_revision = '093b91955d73'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_whisper_account')
    op.alter_column('tb_playsound', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('tb_playsound', 'link',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_playsound', 'link',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.alter_column('tb_playsound', 'enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.create_table('tb_whisper_account',
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('oauth', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('`enabled` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('username'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
