"""remove_filters

Revision ID: f163a00a02aa
Revises: 46d07701a90b
Create Date: 2019-05-30 23:20:40.098349

"""

# revision identifiers, used by Alembic.
revision = "f163a00a02aa"
down_revision = "46d07701a90b"
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tb_filters")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tb_filters",
        sa.Column("id", mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=128), nullable=True),
        sa.Column("type", mysql.VARCHAR(length=64), nullable=True),
        sa.Column("action", mysql.TEXT(), nullable=True),
        sa.Column("extra_args", mysql.TEXT(), nullable=True),
        sa.Column("filter", mysql.TEXT(), nullable=True),
        sa.Column("source", mysql.TEXT(), nullable=True),
        sa.Column("enabled", mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
        sa.Column("num_uses", mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
