#!/usr/bin/env bash

set -euo pipefail

if ! pip -V; then
  >&2 echo "$0"': not inside virtual environment. Try `source venv/bin/activate` or `./install/venvinstall.sh`'
  exit 1
fi

pip install mysqlclient==1.4.4

python ./migrate-mysql-to-postgresql.py

pip uninstall mysqlclient
